<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MFLInwardWalletMISPayTMPos extends Model {
  use HasFactory;


  protected $table = 'MFL_inward_WalletMIS_PayTMPos';

  protected $primaryKey = 'payTMPosUID';


  protected $fillable = [
    'colBank',
    'storeId',
    'merCode',
    'tid',
    'mid',
    'depositDt',
    'crDt',
    'depositAmount',
    'msfComm',
    'cgstAmt',
    'sgstAmt',
    'igstAmt',
    'totalGst',
    'netAmt',
    'terminalName',
    'orderID',
    'storeName',
    'utrNo',
    'payoutDate',
    'externalSerialNo',
    'tranID',
    'instrument',
    'creationDt',
    'payType',
    'payerVPA',
    'payoutID',
    'channel',
    'productCode',
    'requestType',
    'status',
    'settledAmount',
    'pcf',
    'pcfGst',
    'responseCode',
    'responseMessage',
    'originalTxnValue',
    'prepaidCard',
    'additionalComments',
    'chargeTarget',
    'feeFactor',
    'bankGateway',
    'cardScheme',
    'merRefId',
    'merchantTrackID',
    'arnNo',
    'commissionRate',
    'acquiringServiceFee',
    'acquiringServiceTax',
    'platformServiceFee',
    'platformServiceTax',
    'userExpectedCreditDate',
    'settleType',
    'merchantPaymentDetail1',
    'customerID',
    'customerNickName',
    'paymentMobileNumber',
    'paymentEmailID',
    'issuingBank',
    'referenceTransactionID',
    'gmvTier',
    'transactionSlab',
    'refundType',
    'refundActor',
    'splitFlag',
    'splitMID',
    'splitID',
    'paymentReferenceNumber',
    'isPNRValidated',
    'prnValidateTime',
    'creditDebitCardLast4Digits',
    'promoCode',
    'promoResponse',
    'cardBin',
    'customerDetails',
    'linkName',
    'linkNotes',
    'promoDiscountType',
    'promoAmount',
    'totalBillAmount',
    'instantDiscount',
    'mlvAmount',
    'authCode',
    'rrn',
    'promoCartAmount',
    'resellerID',
    'resellerName',
    'employeeID',
    'employeeName',
    'employeePhoneNo',
    'employeeEmail',
    'orderReason',
    'customerAccountNumber',
    'customerBankIFSC',
    'templateID',
    'templateName',
    'foreignCurrency',
    'foreignCurrencyName',
    'foreignAmount',
    'exchangeRate',
    'userMarkupRate',
    'refundSource',
    'subOrderStatus',
    'refundReversalID',
    'refundReversalStatus',
    'refundReversalTimestamp',
    'isReversal',
    'phonepayRefId',
    'serviceProvider',
    'bankRef',
    'isActive',
    'createdBy',
    'createdDate',
    'modifiedBy',
    'modifiedDate',
    'missingRemarks',
    'unAllocatedRemarks',
    'unAllocatedCorrectionDate',
    'unAllocatedStatus',
    'storeID',
    'retekCode',
    'brand',
  ];

  public $timestamps = false;


}